// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volta.Stocks.Infrastructure;

namespace Volta.Stocks.Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20201212212547_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Volta.Stock")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Volta.Stocks.Domain.Stocks.Stock", b =>
                {
                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("StockId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Volta.Stocks.Domain.Stocks.Stock", b =>
                {
                    b.OwnsOne("Volta.Stocks.Domain.Stocks.Services.LiveStockData", "LiveStockData", b1 =>
                        {
                            b1.Property<Guid>("StockId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("DividendYield")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DividendYield");

                            b1.Property<long>("MarketCap")
                                .HasColumnType("bigint")
                                .HasColumnName("MarketCap");

                            b1.Property<decimal>("PeRatio")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PeRatio");

                            b1.Property<decimal>("PegRatio")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PegRatio");

                            b1.Property<decimal>("PriceToBookRatio")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceToBookRatio");

                            b1.Property<decimal>("ProfitMargin")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ProfitMargin");

                            b1.Property<long>("TotalRevenue")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalRevenue");

                            b1.HasKey("StockId");

                            b1.ToTable("Stocks");

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("LiveStockData");
                });
#pragma warning restore 612, 618
        }
    }
}
